[project]
name = "ninja-navigator-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "langgraph>=0.5.4",
    "pandas>=2.3.1",
    "setuptools>=80.9.0",
]
